### ISSUE TITLE
encoding problems

### ISSUE THREAD

**Issue by seebi** [nsmgr8/vitra#4]
I have a problem with the content which is returned by trac.

In vim, all buffers are loaded with "No Encoding" but trac's rpc returns UTF8 which means there are encoding errors e.g. for german umlauts and other non-ascii chars.

**Comment by nsmgr8** [comment]
This is a known problem. I am trying to learn encodings between python and vimscript. If you have any good information on vim encodings, do let me know. You may also share your vimrc settings for encoding that makes vim understand utf-8.

**Comment by seebi** [comment]
Its just:

```
set encoding=utf-8  " Sets the character encoding used inside Vim.
```

**Comment by seebi** [comment]
Opening a ticket, I got these errors:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/seebi/.vim/bundle/vitra/plugin/vitra.py", line 1047, in ticket_view
    self.uiticket.update(contents, titles)
  File "/home/seebi/.vim/bundle/vitra/plugin/vitra.py", line 192, in update
    self.windows[window].write(contents[window])
  File "/home/seebi/.vim/bundle/vitra/plugin/vitra.py", line 141, in write
    self.on_write()
  File "/home/seebi/.vim/bundle/vitra/plugin/vitra.py", line 346, in on_write
    a.replace('/', '\/')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 17: ordinal not in range(128)
```

**Comment by nsmgr8** [comment]
I have just pushed an update. This will fix your second issue. However, the main issue isn't resolved yet.

**Comment by seebi** [comment]
I've upgraded but the UnicodeEncodeError still apears ...

**Comment by nsmgr8** [comment]
Is it the same error? I mean is it at

```
a.replace...
```

**Comment by seebi** [comment]
after a plain `TTOpen` I get

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/seebi/.vim/bundle/vitra/plugin/vitra.py", line 1091, in ticket_view
    self.uiticket.update(contents, titles)
  File "/home/seebi/.vim/bundle/vitra/plugin/vitra.py", line 217, in update
    self.windows[window].content = contents[window]
  File "/home/seebi/.vim/bundle/vitra/plugin/vitra.py", line 168, in content
    self.on_write()
  File "/home/seebi/.vim/bundle/vitra/plugin/vitra.py", line 371, in on_write
    a.replace(u'/', u'\/')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 40: ordinal not in range(128)
```

**Comment by seebi** [comment]
And on a `TWSave` I get

```
Error: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)
```

**Comment by nsmgr8** [comment]
I have updated the code again. Please check whether it has solved the issue. Thanks.

**Comment by nicph** [comment]
I experienced some issues too with unicode, because of trac milestones or components containing unicode characters. Your last change fixes some of them (i am now able to load the complete ticket list for example), but i still get some issue on command completion. My next pull request fixes the issues i met.

**Comment by seebi** [comment]
ok, with the current version 2470ad4 I can do the following:
- TWOpen a page with non-ascii chars
- edit the wiki page
- save it without an error

This same is unfortunately not true for TTOpen. There comes again:

```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 40: ordinal not in range(128)
```

**Comment by nsmgr8** [comment]
There is an update now. Thanks to [nicolasph](https://github.com/nicolasph) vitra is now able to load with correct encoding. There is one issue left though. The command completion will not fail now, but it will give ascii encoding. Therefore a bit less useful if you have too many non-ascii chars in several fields and actions.

**Comment by seebi** [comment]
alright, I do not have any encoding errors anymore. Thank you very much!
